name: Send a telegram message when new hot subreddit
on:
  reddit:
    url: https://reddit.com/r/news/
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: <a href=\"${{ on.reddit.outputs.link }}\">${{ on.reddit.outputs.title }}</a> 
          format: html
